version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_PORT}:80"  # Map the dynamic port to container's port 80 (NGINX default)
    environment:
      - NODE_ENV=production
    networks:
      - reactnet

networks:
  reactnet:
    driver: bridge
